<link rel="stylesheet" href="{{ asset('/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('/css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ asset('/css/flaticon.css') }}">
<link rel="stylesheet" href="{{ asset('/css/slicknav.css') }}">
<link rel="stylesheet" href="{{ asset('/css/animate.min.css') }}">
<link rel="stylesheet" href="{{ asset('/css/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('/css/fontawesome-all.min.css') }}">
<link rel="stylesheet" href="{{ asset('/css/themify-icons.css') }}">
<link rel="stylesheet" href="{{ asset('/css/slick.css') }}">
<link rel="stylesheet" href="{{ asset('/css/nice-select.css') }}">
<link rel="stylesheet" href="{{ asset('/css/style.css') }}">